---
.cache_bundler: &cache_bundler
  cache:
    untracked: true
    # A broad attempt at caching between runs (ala Travis CI)
    key: "${CI_PROJECT_NAMESPACE}__bundler"
    paths:
      - '.vendor'
      - 'vendor'

.setup_bundler_env: &setup_bundler_env
  before_script:
    - 'echo Files in cache: $(find .vendor | wc -l) || :'
    - 'export GEM_HOME=.vendor/gem_install'
    - 'export BUNDLE_CACHE_PATH=.vendor/bundler'
    - 'declare GEM_BUNDLER_VER=(-v ''~> ${BUNDLER_VERSION:-1.16.0}'')'
    - declare GEM_INSTALL=(gem install --no-document)
    - declare BUNDLER_INSTALL=(bundle install --no-binstubs --jobs $(nproc) --path=.vendor "${FLAGS[@]}")
    - gem list -ie "${GEM_BUNDLE_VER[@]}" --silent bundler || "${GEM_INSTALL[@]}" --local "${GEM_BUNDLE_VER[@]}" bundler || "${GEM_INSTALL[@]}" "${GEM_BUNDLE_VER[@]}" bundler
    - 'rm -rf pkg/ || :'
    - bundle check || rm -f Gemfile.lock && ("${BUNDLER_INSTALL[@]}" --local || "${BUNDLER_INSTALL[@]}")


.validation_checks: &validation_checks
  script:
    - bundle exec rake syntax
    - bundle exec rake check:dot_underscore
    - bundle exec rake check:test_file
    - bundle exec rake pkg:check_version
    - bundle exec rake pkg:compare_latest_tag
    - bundle exec rake lint
    - bundle exec rake clean
    - bundle exec puppet module build

stages:
  - unit
  - acceptance
  - deploy

# Puppet 4
puppet-gemfile:
  stage: unit
  tags:
    - docker
  image: ruby:2.1.9
  <<: *cache_bundler
  <<: *setup_bundler_env
  <<: *validation_checks

# For PE LTS Support
# See: https://puppet.com/misc/puppet-enterprise-lifecycle
puppet-4.7:
  stage: unit
  tags:
    - docker
  image: ruby:2.1.9
  variables:
    PUPPET_VERSION: '4.7'
  <<: *cache_bundler
  <<: *setup_bundler_env
  <<: *validation_checks

puppet-5:
  stage: unit
  tags:
    - docker
  image: ruby:2.4
  variables:
    PUPPET_VERSION: '5.0'
  <<: *cache_bundler
  <<: *setup_bundler_env
  <<: *validation_checks


default:
  stage: acceptance
  tags:
    - beaker
  <<: *cache_bundler
  <<: *setup_bundler_env
  variables:
    PUPPET_VERSION: '4.10'
  script:
    - bundle exec rake beaker:suites[default]

ce:
  stage: acceptance
  tags:
    - beaker
  <<: *cache_bundler
  <<: *setup_bundler_env
  variables:
    PUPPET_VERSION: '4.10'
  script:
    - bundle exec rake beaker:suites[ce]

default-fips:
  stage: acceptance
  tags:
    - beaker
  <<: *cache_bundler
  <<: *setup_bundler_env
  variables:
    BEAKER_fips: 'yes'
    PUPPET_VERSION: '4.10'
  script:
    - bundle exec rake beaker:suites[default]

ce-fips:
  stage: acceptance
  tags:
    - beaker
  <<: *cache_bundler
  <<: *setup_bundler_env
  variables:
    PUPPET_VERSION: '4.10'
    BEAKER_fips: 'yes'
  script:
    - bundle exec rake beaker:suites[ce]

default-latest:
  stage: acceptance
  tags:
    - beaker
  <<: *cache_bundler
  <<: *setup_bundler_env
  variables:
    PUPPET_VERSION: '5.0.0'
  script:
    - bundle exec rake beaker:suites[default]
  allow_failure: true
